//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DankaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int maAdmin { get; set; }
        public string hoTenAdmin { get; set; }
        public string diaChiAdmin { get; set; }
        public string dienThoaiAdmin { get; set; }
        public string tenDnAdmin { get; set; }
        public string matKhauAdmin { get; set; }
        public Nullable<System.DateTime> ngaySinhAdmin { get; set; }
        public Nullable<bool> gioiTinhAdmin { get; set; }
        public string emailAdmin { get; set; }
        public Nullable<int> quyenAdmin { get; set; }
    }
}
