//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DankaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdathang
    {
        public int soDh { get; set; }
        public int maKhoahoc { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<decimal> donGia { get; set; }
        public Nullable<decimal> thanhTien { get; set; }
    
        public virtual dondathang dondathang { get; set; }
        public virtual Khoahocedm Khoahocedm { get; set; }
    }
}
