//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DankaFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanKaEDMEntities : DbContext
    {
        public DanKaEDMEntities()
            : base("name=DanKaEDMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<ctdathang> ctdathangs { get; set; }
        public virtual DbSet<dondathang> dondathangs { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<Khoahocedm> Khoahocedms { get; set; }
        public virtual DbSet<quangcao> quangcaos { get; set; }
        public virtual DbSet<theloai> theloais { get; set; }
    }
}
