//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DankaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.dondathangs = new HashSet<dondathang>();
        }
    
        public int maKh { get; set; }
        public string hoTenkh { get; set; }
        public string diaChikh { get; set; }
        public string dienThoaikh { get; set; }
        public string tenDn { get; set; }
        public string matKhau { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dondathang> dondathangs { get; set; }
    }
}
